import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { createSupabaseServerClient } from "../utils/supabaseServer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export async function getPosts() {
  const supabase = createSupabaseServerClient();
  const { data, error } = await supabase.from("post").select("*");
  if (error) {
    throw error;
  }
  return data;
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
